name: build-push.yml

on:
  push:
    branches: [ main, fix-gha-yes ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/hamct:lulu
            ${{ secrets.DOCKER_HUB_USERNAME }}/hamct:test
            ${{ secrets.DOCKER_HUB_USERNAME }}/hamct:${{ github.event.pull_request.base.sha }}
