name: PR Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: ktlint
        run: mvn ktlint:check

      - name: Run tests
        run: mvn clean test
